### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.q.b(android.view.MotionEvent)' on a null object reference

### ISSUE THREAD

**Issue by zoey-yang** [StraaS/StraaS-android-sdk-sample#131]
Hi,

Our app crashed if user click emoji button which at the bottom of chatroom

SDK: messaging-ui
SDK version: 0.8.2
Android OS version: 7.1.1
Google Play Services version: 11.8.0
Android Support Library version: 27.0.2

Crash log as below
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: net.ettoday.phone, PID: 14011
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.q.b(android.view.MotionEvent)' on a null object reference
                                                       at biz.laenger.android.vpbs.ViewPagerBottomSheetBehavior.b(ViewPagerBottomSheetBehavior.java:320)
                                                       at android.support.design.widget.CoordinatorLayout.a(CoordinatorLayout.java:389)
                                                       at android.support.design.widget.CoordinatorLayout.onAttachedToWindow(CoordinatorLayout.java:235)
                                                       at android.view.View.dispatchAttachedToWindow(View.java:15561)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:241)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by b95505017** [comment]
Should be fixed in #136
