### ISSUE TITLE
Exception while inflating org.xmlpull.v1.XmlPullParserException:

### ISSUE THREAD

**Issue by LyonHsu** [StraaS/StraaS-android-sdk-sample#19]
Welcome to StraaS.io and thanks for submitting an issue!

Please search the existing issues before filing a new one, including issues that
are closed. 

Please feel free to fill in the following info so we can help faster!
### Step 1: Are you in the right place? YES
- For issues or feature requests related to the code or document provided **in this repository** file a GitHub issue.
- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/).
### Step 2: Describe your environment
- SDK: [messaging-ui| messaging| media-core| extension-ima]
- SDK version: **0.3.10_**
- Android device: **SAMSUNG Tab 7_**
- Android OS version: _4.4.2____
- Google Play Services version: _____
### Step 3: Describe the problem:
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using `adb bugreport`. Output from `adb
  logcat` or a log snippet is not sufficient.
#### Steps to reproduce:
- Steps describing how the issue can be reproduced, ideally in the demo app.
  
  when I touch the editText then show the "app have stop" alert
#### Observed Results:
- What happened?  This could be a description, `log` output, etc.
#### Expected Results:
- What did you expect to happen?
#### Relevant Code:

tw.friday.video.hd E/VdcInflateDelegate: Exception while inflating <vector>
                                                                      org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                                          at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:541)
                                                                          at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:478)
                                                                          at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:441)
                                                                          at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:742)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:362)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                          at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                          at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                          at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                          at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:190)
                                                                          at android.support.v7.app.AppCompatDialog.getDelegate(AppCompatDialog.java:152)
                                                                          at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:49)
                                                                          at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:95)
                                                                          at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:927)
                                                                          at io.straas.android.sdk.messaging.ui.ChatroomView.c(Unknown Source)
                                                                          at io.straas.android.sdk.messaging.ui.ChatroomView.p(Unknown Source)
                                                                          at io.straas.android.sdk.messaging.ui.ChatroomView$5.onTouch(Unknown Source)
                                                                          at android.view.View.dispatchTouchEvent(View.java:8040)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java
10-27 13:41:48.040 2278-2278/tw.friday.video.hd E/InputEventReceiver: Exception dispatching input event.
10-27 13:41:48.050 2278-2278/tw.friday.video.hd E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
10-27 13:41:48.075 2278-2278/tw.friday.video.hd E/MessageQueue-JNI: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                                        at android.content.res.Resources.loadDrawable(Resources.java:3430)
                                                                        at android.content.res.Resources.getDrawable(Resources.java:1917)
                                                                        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
                                                                        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
                                                                        at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
                                                                        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                        at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                        at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                        at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                        at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                        at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                                        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
                                                                        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:190)
                                                                        at android.support.v7.app.AppCompatDialog.getDelegate(AppCompatDialog.java:152)
                                                                        at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:49)
                                                                        at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:95)
                                                                        at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:927)
                                                                        at io.straas.android.sdk.messaging.ui.ChatroomView.c(Unknown Source)
                                                                        at io.straas.android.sdk.messaging.ui.ChatroomView.p(Unknown Source)
                                                                        at io.straas.android.sdk.messaging.ui.ChatroomView$5.onTouch(Unknown Source)
                                                                        at android.view.View.dispatchTouchEvent(View.java:8040)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.ja
10-27 13:41:48.075 2278-2278/tw.friday.video.hd D/AndroidRuntime: Shutting down VM
10-27 13:41:48.075 2278-2278/tw.friday.video.hd W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4170ac08)
10-27 13:41:48.100 2278-2278/tw.friday.video.hd E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: tw.friday.video.hd, PID: 2278
                                                                  android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
                                                                      at android.content.res.Resources.loadDrawable(Resources.java:3430)
                                                                      at android.content.res.Resources.getDrawable(Resources.java:1917)
                                                                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                      at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                      at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                      at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                      at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                      at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                                      at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
                                                                      at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:190)
                                                                      at android.support.v7.app.AppCompatDialog.getDelegate(AppCompatDialog.java:152)
                                                                      at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:49)
                                                                      at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:95)
                                                                      at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:927)
                                                                      at io.straas.android.sdk.messaging.ui.ChatroomView.c(Unknown Source)
                                                                      at io.straas.android.sdk.messaging.ui.ChatroomView.p(Unknown Source)
                                                                      at io.straas.android.sdk.messaging.ui.ChatroomView$5.onTouch(Unknown Source)
                                                                      at android.view.View.dispatchTouchEvent(View.java:8040)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2121)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
                                                                    at android.view.ViewGroup.dispatchTo

**Comment by b95505017** [comment]
Hi Lyon, thanks for reporting this issue.
Could you reproduce this issue on our sample?

**Comment by LyonHsu** [comment]
Dear 
I can't reproduce this issue on your sample.
This issue is serious that crash in code,  and I can't fix in my way.

you can see the log error 
 io.straas.android.sdk.messaging.ui.ChatroomView.c 

The issue can't reproduce in other device, just find in Samsung Galaxy Tab 4 7.0 4G LTE (SM-T235Y) now.

**Comment by b95505017** [comment]
Hi Lyon,
Does it means that sample works normally on SM-T235Y?
If so, maybe the issue is caused by build.gradle setting, please make sure you have the same setting with our sample, or please provide an reproducible sample project to us.

Thanks.

**Comment by LyonHsu** [comment]
dear 
I find the issue is created by  at android.support.v7.app.AlertDialog in 4.4.2 (API 19)  Issue 201835
Maybe you cat use the   android.app.AlertDialog

**Comment by b95505017** [comment]
Nope it shouldn't be a problem. Support library does all the handling about vector drawable unless there are something wrong about your development environment.

I'm confused about your reply, sorry.
>I can't reproduce this issue on your sample.

Does our sample run well on SM-T235Y?
